---
locale: es
tags: []
layout: input_bottom
editor: single_choice
type: problem
extra_visible: false
language: text
teacher_info: ''
manual_evaluation: false
choices:
- !ruby/hash:ActiveSupport::HashWithIndifferentAccess
  value: Na linguagem de programação _Cobra_.
  checked: false
- !ruby/hash:ActiveSupport::HashWithIndifferentAccess
  value: Nos humoristas britânicos _Monty Python_.
  checked: true
- !ruby/hash:ActiveSupport::HashWithIndifferentAccess
  value: Na picada da serpente que o criador sofreu.
  checked: false
name: O sentido de Python
