---
locale: es
tags: []
layout: input_bottom
editor: 0
type: interactive
extra_visible: false
teacher_info: ''
manual_evaluation: false
choices: []
goal: !ruby/hash:ActiveSupport::HashWithIndifferentAccess
  kind: last_query_matches
  regexp: str.startswith(\W*"caracol"\W*,\W*"cara"\W*)\W+and\W+str.endswith(\W*"caracol"\W*,\W*"col"\W*)
name: No olvidemos los booleanos
