---
locale: pt
tags: []
layout: input_bottom
editor: 0
type: interactive
extra_visible: false
teacher_info: ''
manual_evaluation: false
progressive_expectations: false
choices: []
goal:
  kind: last_query_matches
  regexp: 8[ ]*!=[ ]*8
name: Nem tudo é um número
