---
locale: pt
tags: []
layout: input_bottom
editor: multiple_choice
type: problem
extra_visible: false
language: text
teacher_info: ''
manual_evaluation: false
progressive_expectations: false
choices:
- value: "`4 + 4` vale `8`"
  checked: true
- value: '`"4" + "4"` vale `"44"`'
  checked: true
- value: '`4 + 4` vale `"44"`'
  checked: false
- value: '`"on" + "ze"` vale `"onze"`'
  checked: true
- value: "`True and False` vale `False`"
  checked: true
- value: "`True and False` vale `0`"
  checked: false
- value: "`5 >= 6` vale `False`"
  checked: true
name: Um pouco de cada tipo
